version: "3.9"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/uploads:/app/uploads
    expose:
      - "8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    command: echo "Frontend built in container (static files copied to backend)"
    volumes:
      - ./frontend/build:/frontend/build

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

